config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  resources :users, only: :new
  
  resources :cart_items 

  resources :orders, only: [:index, :create]
  
  resources :carts  
  
  namespace :admin do
    resources :user_sessions, only: :new 
  end
  root to: 'items#index'
  
  resources :items, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  
  resources :proteins 

end
 

app/models/add.rb
class Add < ApplicationRecord
  belongs_to :shohin
end

app/models/bento.rb
class Bento < ApplicationRecord
  belongs_to :user
  belongs_to :calo
  has_one :deli
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  belongs_to :protein
  has_one :delivery
end

app/models/calo.rb
class Calo < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :bento

  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/ },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :proteins, through: :cart_items
  has_one :order
  
  #sessionの中身と紐付く内容
  def add_protein(protein_id)
    current_item = cart_items.find_by_protein_id(protein_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(protein_id: protein_id)
    end
      current_item
  end

  
  def total_price
    current_price = cart_items.to_a.sum {|item| item.total_price } 
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :protein
  belongs_to :cart

  def total_price
    protein.price * quantity 
  end

end

app/models/deli.rb
class Deli < ApplicationRecord
  belongs_to :bento
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :buyer
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :image


  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).to_f*100/5
    else
      0.0
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :purchase
  belongs_to :cart
end

app/models/protein.rb
class Protein < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :buyer
  has_many :cart_items
  before_destroy :referenced_by_cart_item


  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/i },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end

  private 
  def referenced_by_cart_item
    if cart_items.empty?
      return true
    else
      errors.add(:base, '品目が存在します。')
      retuen false
    end
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :order
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user


  with_options presence: true do
    validates :score
    validates :content
  end

end

app/models/shohin.rb
class Shohin < ApplicationRecord
  belongs_to :user
  belongs_to :soft
  has_one :add
end

app/models/soft.rb
class Soft < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :shohin
  
  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/ },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :proteins
  has_many :softs
  has_many :calos
  has_many :reviews, dependent: :destroy
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      email: auth.info.email)
    # userが登録済みが判断
    if user.persisted?
      sns.user = user
      sns.save
    end
    {user: user, sns: sns }
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  with_options presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :last_name
    validates :first_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/} do
    validates :last_name_kana
    validates :first_name_kana
  end

  
    validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
    validates :email, uniqueness: { case_sensitive: true }

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calos_helper.rb
module CalosHelper
end

app/views/shared/_error_messages.html.erb
<%if model.errors.any? %>
<div class="error-alert">
  <ul>
  <% model.errors.full_messages.each do |message| %>
  <li class='error-message'><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='bento-details'>
      <h2 class='footer-content-head'>HelthLunchについて</h2>
      <ul>
        <li>会社概要</li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
    <div class='bento-details'>
      <h2 class='footer-content-head'>HelthLunchについて</h2>
      <ul>
        <li>HelthLunch一覧</li>
        <li></li>
        <li></li>
      </ul>
    </div>
  </div>
  <div class='purchase-btn'>
</div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='header-contents-menu'>
    <div class='bar-contents'>
      <p class='title-header'></p>
    </div>
    <div class='search-bar-contents'>
      <div class='header-title'>
        <%= link_to 'HealthLunch', root_path, method: :get, class: "healthLunch"%>
      </div>
    </div>
      <div class="cp_cont">
	      <div class="cp_offcm04">
          <input type="checkbox" id="cp_toggle04">
          <label for="cp_toggle04"><span></span></label>
          <div class="cp_menu">
          <ul >
          <% if user_signed_in? %>
           <div class='first_name'><%= "#{current_user.first_name}" %><%="#{current_user.last_name}" %>のマイページ</div>
           <li><%=link_to 'ログアウト',destroy_user_session_path, method: :delete, class: "logout"%></li>
          <% else %>
           <li><%=link_to 'ログイン', new_user_session_path, class: "login" %></li>
           <li><%=link_to '新規登録', new_user_registration_path, class: "sign_up"%></li>
          <% end %>
            <li><%= link_to 'メニュー一覧', proteins_path  %>
            <%# <li><%= link_to 'カロリーケア', calos_path %></li> 
            <%# <li><%= link_to 'やわらか食事', softs_path %></li> 
            <li><%= link_to 'よくある質問', "#" %></li>
            <li><%= link_to 'トップページへ戻る', root_path %></li>
            <% if user_signed_in? %>
              <% if current_user == @user || current_user.admin? %>
                <li class='admin'><%= link_to '商品登録', new_protein_path %></li>
              <% end %>
            <% end %>
            <%# <% if user_signed_in? %>
              <%# <% if current_user == @user || current_user.admin? %> 
                <%# <li class='admin'><%= link_to 'やわらか商品登録', new_soft_path %>
              <%# <% end %> 
            <%# <% end %> 
            <%# <% if user_signed_in? %> 
              <%# <% if current_user == @user || current_user.admin? %> 
                <%# <li class='admin'><%= link_to 'カロリー商品登録', new_calo_path %>
              <%# <% end %> 
            <%# <% end %> 
          </ul>
          </div>
        </div>
      </div>
    </div>
    <div class='bar-contents'>
      <p class='title-header'></p>
    </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>HealthLunth利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "111173.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= image_tag("111173.png", class:'second-logo') %>
</header>