config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  resources :users, only: :new
  
  resources :cart_items 

  resources :orders, only: [:index, :create]
  
  resources :carts  
  
  namespace :admin do
    resources :user_sessions, only: :new 
  end
  root to: 'items#index'
  
  resources :items, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  
  resources :proteins 

end
 

app/models/add.rb
class Add < ApplicationRecord
  belongs_to :shohin
end

app/models/bento.rb
class Bento < ApplicationRecord
  belongs_to :user
  belongs_to :calo
  has_one :deli
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  belongs_to :protein
  has_one :delivery
end

app/models/calo.rb
class Calo < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :bento

  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/ },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :proteins, through: :cart_items
  has_one :order
  
  #sessionの中身と紐付く内容
  def add_protein(protein_id)
    current_item = cart_items.find_by_protein_id(protein_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(protein_id: protein_id)
    end
      current_item
  end

  
  def total_price
    current_price = cart_items.to_a.sum {|item| item.total_price } 
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :protein
  belongs_to :cart

  def total_price
    protein.price * quantity 
  end

end

app/models/deli.rb
class Deli < ApplicationRecord
  belongs_to :bento
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :buyer
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :image


  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).to_f*100/5
    else
      0.0
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :purchase
  belongs_to :cart
end

app/models/protein.rb
class Protein < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :buyer
  has_many :cart_items
  before_destroy :referenced_by_cart_item


  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/i },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end

  private 
  def referenced_by_cart_item
    if cart_items.empty?
      return true
    else
      errors.add(:base, '品目が存在します。')
      retuen false
    end
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :order
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user


  with_options presence: true do
    validates :score
    validates :content
  end

end

app/models/shohin.rb
class Shohin < ApplicationRecord
  belongs_to :user
  belongs_to :soft
  has_one :add
end

app/models/soft.rb
class Soft < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :shohin
  
  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/ },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :proteins
  has_many :softs
  has_many :calos
  has_many :reviews, dependent: :destroy
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      email: auth.info.email)
    # userが登録済みが判断
    if user.persisted?
      sns.user = user
      sns.save
    end
    {user: user, sns: sns }
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  with_options presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :last_name
    validates :first_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/} do
    validates :last_name_kana
    validates :first_name_kana
  end

  
    validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
    validates :email, uniqueness: { case_sensitive: true }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @review = Review.new
  end 

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calos_helper.rb
module CalosHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>
    <div class='title-contents'>
    <div id="pic_src"></div>
      <h1 class='advertising'>
        おうちご飯を応援
      </h1>
      <p class='picture-contents'>
        栄養士考案のバランスが取れたお弁当
      </p>
      <p class='picture-contents'>
        食事から健康をサポート致します!
      </p>
    </div>
    <div class='select-reason-contents'>
      <h2 class='title'>
        メニュー
      </h2>
    </div>
    <div class='bentos-lists'>
      <ul class='bento-lists'>
        <li class='list'>
          <%= link_to(proteins_path) do %>
            <%= image_tag "b1.jpg", class: "list-pict" %> 
          <% end %>
          <h3 class='bento-list-text'>
          メニュー一覧はこちら
          </h3>
          <p class='bento-list-title'>
            介護食弁当
          </p>
          <p class='bento-list-explain'>
            見た目もそのまま！歯茎で潰せる食事
          </p>
        </li>
      </ul>
    </div>
    <div class='feature-contents'>
      <h2 class='second-health-title'>
        HealthLunchが選ばれる理由
      </h2>
      <div class='textArea'>
        <div class='text-Box'>
          <div class='discBox'>
            <h3 class='menu-acount'>1.管理栄養士監修で安心</h3>
            <p class='acount'>
            管理栄養士・栄養士が考案した弁当の宅配サービス。食の基本であるおいしさにこだわりながら、カロリーや塩分に配慮したメニューの豊富さ！
            </p>
          </div>
        </div>
        <div class='text-Box'>
          <div class="discBox">
            <h3 class='menu-acount'>2.冷凍だから食べたい時にすぐ美味しい</h3>
            <p class='acount'>
            冷凍でお届けするので、食べたいときにチンするだけ！決められた時間に縛られることなく、自分のペースで食べられる！
            </p>
          </div>
        </div>
      </div>
    </div>
  <section class='section'>
    <div class='review-container'>
      <div class='columns is-centered'>
        <div class='column is-5'>
          <% @items.each do |item| %>
            <div class="card mb-6">
              <div class="card-header">
                <p class="card-heder-title">
                  <%= item.name %>
                </p>
              </div>
              <div class="card-content">
                <div calss="content">
                  <div class="content average-score">
                    <div class="star-rating mb-2">
                      <div class="star-rating-front" style="width: <%= item.review_score_percentage %>%">★★★★★</div>
                      <div class="star-rating-back">★★★★★</div>
                    </div>
                    <div class ="average-score-display ml-3 pt-2">
                    <%= item.avg_score %>点(<%= item.reviews.count %>件)
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <%= link_to item_reviews_path(item), class: "button card-footer-item" do %>
                  レビューを見る
                <% end %>
                <%= link_to item_path(item), class: "button card-footer-item" do %>
                  レビューを書く
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%# <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %> 

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: items_path, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# <%= render 'shared/error_messages', model: f.object %>  
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
        <%# <%= image_tag @item.image, class: 'img-upload' if @item.image.attached? %> 
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :acount, class:"items-text", id:"item-info" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price" %>
        </div>
        <div class="price-content">
          <span>配送料</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売価格(税込み)</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>
     <div class="price-content">
          <div class="price-text">
            <span>エネルギー</span>
          </div>
          <%= f.text_field :energy, class:"price-input" %>
      </div>
        <div class="price-content">
          <div class="price-text">
            <span>たんぱく質</span>
          </div>
          <%= f.text_field :prote, class:"price-input" %>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>脂質</span>
          </div>
          <%= f.text_field :Lipid, class:"price-input" %>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>塩分</span>
          </div>
          <%= f.text_field :salt, class:"price-input" %>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>炭水化物</span>
          </div>
          <%= f.text_field :carbo, class:"price-input" %>
        </div>
    <div class="sell-btn-contents">
      <%= f.submit "たんぱくケア" ,class:"sell-btn" %>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "カロリーケア" ,class:"sell-btn" %> 
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "やわらかメニュー" ,class:"sell-btn"%> 
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
<div>

app/views/items/show.html.erb
<%= render "shared/header" %>
<section class='section'>
  <div class='review-container'>
    <div class='columns is-centered'>
      <div class='column is-5'>
          <div class='card mb-6'>
            <header class='card-header'>
              <p class='card-heder-title'>
                <%= @item.name %>
              </p>
            </header>
            <div class="card-content">
              <div class='content average-score'>
                <div class='star-rating mb-2'>
                  <div class='star-rating-front' style='width:<%= @item.review_score_percentage %>%'>★★★★★</div>
                  <div class='star-rating-back'>★★★★★</div>
                </div>
                <div class ='average-score-display ml-3 pt-2'>
                  <%= @item.avg_score %>点(<%= @item.reviews.count %>件のレビュー)
                </div>
              </div>
            </div>
          </div>
        <%= render 'reviews/form', review: @review, item: @item %>
      </div>
    </div>
  </div>
  </section>