config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  resources :users, only: :new
  
  resources :cart_items 

  resources :orders, only: [:index, :create]
  
  resources :carts  
  
  namespace :admin do
    resources :user_sessions, only: :new 
  end
  root to: 'items#index'
  
  resources :items, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  
  resources :proteins 

end
 

app/models/add.rb
class Add < ApplicationRecord
  belongs_to :shohin
end

app/models/bento.rb
class Bento < ApplicationRecord
  belongs_to :user
  belongs_to :calo
  has_one :deli
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  belongs_to :protein
  has_one :delivery
end

app/models/calo.rb
class Calo < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :bento

  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/ },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :proteins, through: :cart_items
  has_one :order
  
  #sessionの中身と紐付く内容
  def add_protein(protein_id)
    current_item = cart_items.find_by_protein_id(protein_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(protein_id: protein_id)
    end
      current_item
  end

  
  def total_price
    current_price = cart_items.to_a.sum {|item| item.total_price } 
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :protein
  belongs_to :cart

  def total_price
    protein.price * quantity 
  end

end

app/models/deli.rb
class Deli < ApplicationRecord
  belongs_to :bento
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :buyer
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :image


  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).to_f*100/5
    else
      0.0
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :purchase
  belongs_to :cart
end

app/models/protein.rb
class Protein < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :buyer
  has_many :cart_items
  before_destroy :referenced_by_cart_item


  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/i },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end

  private 
  def referenced_by_cart_item
    if cart_items.empty?
      return true
    else
      errors.add(:base, '品目が存在します。')
      retuen false
    end
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :order
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user


  with_options presence: true do
    validates :score
    validates :content
  end

end

app/models/shohin.rb
class Shohin < ApplicationRecord
  belongs_to :user
  belongs_to :soft
  has_one :add
end

app/models/soft.rb
class Soft < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :shohin
  
  with_options presence:true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
    validates :price, format: { with: /\A[0-9]+\z/ },numericality: { only_integer: true}
  end
  
  with_options presence: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ } do
    validates :energy
    validates :prote
    validates :Lipid
    validates :salt
    validates :carbo
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ } do
    validates :first
    validates :second
    validates :third
    validates :forth
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :proteins
  has_many :softs
  has_many :calos
  has_many :reviews, dependent: :destroy
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      email: auth.info.email)
    # userが登録済みが判断
    if user.persisted?
      sns.user = user
      sns.save
    end
    {user: user, sns: sns }
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  with_options presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :last_name
    validates :first_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/} do
    validates :last_name_kana
    validates :first_name_kana
  end

  
    validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
    validates :email, uniqueness: { case_sensitive: true }

end

app/controllers/proteins_controller.rb
class ProteinsController < ApplicationController

  # ログインしていないユーザーはindex,show以外URL直接打ち込んでもトップ画面へ戻る
  before_action :authenticate_user!, except: [:index, :show]
  # ログインしていないユーザーはindex,show以外URL直接打ち込んでもトップ画面へ戻る
  #管理者のみnew,editへの遷移可能
  before_action :move_to_new, only: [:new, :edit]
  #管理者のみnew,editへの遷移可能
  before_action :item_set,  only: [:show, :edit, :update, :destroy]

  def index
    @proteins = Protein.all
  end
  
  def new
    @protein = Protein.new
  end
  
  def create
    @protein = Protein.new(proteins_params)
    if @protein.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @protein.update(proteins_params)
      redirect_to protein_path
    else
      render :edit
    end
  end
  
  def destroy
    if @protein.destroy
      redirect_to proteins_path
    else
      render :show
    end
  end
  
  
  
  private


  
  #管理者のみnew,editへURL直接打ち込んでの遷移可能
  def move_to_new
    unless current_user == @user || current_user.admin?
      redirect_to root_path
    end
  end
  #管理者のみnew,editへURL直接打ち込んでの遷移可能
  

  def item_set
    @protein = Protein.find(params[:id])
  end
  
    def proteins_params
      params.require(:protein).permit(:image, :name, :price, :energy, :prote, :salt, :Lipid, :carbo, :first, :second, :third, :forth,:fifth, cart_ids: []).merge(user_id: current_user.id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calos_helper.rb
module CalosHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/proteins_helper.rb
module ProteinsHelper
end

app/views/proteins/_form.html.erb
<div class="fields">
  <%= collection_check_boxes :protein, :cart_ids, Cart.all, :id, quantity %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/proteins/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の編集を入力</h2>
    <%= form_with model: @protein, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %> 
    <div class='new-contents'>
      <div class="img-upload">
        <div class="weight-bold-text">
          弁当画像
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %> 
        </div>
      </div>
      <div class="new-items">
        <div class="weight-bold-text">
          弁当名
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name" %>
      </div>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price" %>
          </div>
          <div class="price-content">
            <span>販売価格（税込み）</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
        </div>
      </div>
        <div class='contents-protein'>
          <div class="eiyou-content">
              <div class="eiyou-text">
                <span>エネルギー</span>
              </div>
              <%= f.text_field :energy, class:"price-input" %>
          </div>
          <div class="eiyou-content">
            <div class="eiyou-text">
              <span>たんぱく質</span>
            </div>
            <%= f.text_field :prote, class:"price-input" %>
          </div>
          <div class="eiyou-content">
            <div class="eiyou-text">
              <span>脂質</span>
            </div>
            <%= f.text_field :Lipid, class:"price-input" %>
          </div>
          <div class="eiyou-content">
            <div class="eiyou-text">
              <span>塩分</span>
            </div>
            <%= f.text_field :salt, class:"price-input" %>
          </div>
          <div class="eiyou-content">
            <div class="eiyou-text">
              <span>炭水化物</span>
            </div>
            <%= f.text_field :carbo, class:"price-input" %>
          </div>
        </div>
        <div class="bento-menu-text">
          <div class='only-menu'>メニュー</div>
        </div>
        <div class='protein-menus'>
          <div class="menus-contents">
            <%= f.text_field :first, class:"price-input" %>
          </div>
          <div class="menus-contents">
            <%= f.text_field :second, class:"price-input" %>
          </div>
          <div class="menus-contents">
            <%= f.text_field :third, class:"price-input" %>
          </div>
          <div class="menus-contents">
            <%= f.text_field :forth, class:"price-input" %>
          </div>
          <div class="menus-contents">
            <%= f.text_field :fifth, class:"price-input" %>
          </div>
        </div>
    <div class="sell-btn-contents">
      <%= f.submit "たんぱくケア" ,class:"sell-btn" %>
    </div>
    <div class="sell-btn-contents"> 
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    </div>
    <% end %>
  </div>
<div>

app/views/proteins/index.html.erb
<%= render "shared/header" %>

<div class='main-contents'>
  <div class='bento-menu'>
    <div class='main-pic'>
      <div class='pic'>
        <p class='pic-contents'>咀嚼が困難な方、歯茎で潰せるお食事</p>
      </div>
    </div>
    <div class='main-menu'>
      <div class='category-item'>
        <h2 class='title-protein'>メニュー<h2>
      </div>
      <div class='menu-category'>
        <ul class='category-menu'>
          <% @proteins.each do |protein| %>
            <li class='menu'>
              <%= link_to protein_path(protein.id), class: 'link' do%>
                <%= image_tag protein.image, class: 'bento-contents' if protein.image.attached? %>
                <div class="item-info">
                  <h3 class='item-name'><%= protein.name %><h3>
                  <div class='item-price'>
                    <span class='price'><%= protein.price %>円(税抜)</span>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/proteins/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @protein, url: proteins_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %> 
    <div class='new-contents'>
      <div class="img-upload">
        <div class="weight-bold-text">
          弁当画像
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %> 
        </div>
      </div>
      <div class="new-items">
        <div class="weight-bold-text">
          弁当名
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name" %>
      </div>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price" %>
          </div>
          <div class="price-content">
            <span>販売価格（税込み）</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
        </div>
      </div>
        <div class='menus-proteins-contents'>
          <div class='contents-protein'>
            <div class="eiyou-content">
                <div class="eiyou-text">
                  <span>エネルギー</span>
                </div>
                <%= f.text_field :energy, class:"price-input" %>
            </div>
            <div class="eiyou-content">
              <div class="eiyou-text">
                <span>たんぱく質</span>
              </div>
              <%= f.text_field :prote, class:"price-input" %>
            </div>
            <div class="eiyou-content">
              <div class="eiyou-text">
                <span>脂質</span>
              </div>
              <%= f.text_field :Lipid, class:"price-input" %>
            </div>
            <div class="eiyou-content">
              <div class="eiyou-text">
                <span>塩分</span>
              </div>
              <%= f.text_field :salt, class:"price-input" %>
            </div>
            <div class="eiyou-content">
              <div class="eiyou-text">
                <span>炭水化物</span>
              </div>
              <%= f.text_field :carbo, class:"price-input" %>
            </div>
          </div>
          <div class='bento-text-menu'>
            <div class="bento-menu-text">
              <div class='only-menu'>メニュー</div>
            </div>
            <div class='protein-menus'>
              <div class="menus-contents">
                <%= f.text_field :first, class:"price-input" %>
              </div>
              <div class="menus-contents">
                <%= f.text_field :second, class:"price-input" %>
              </div>
              <div class="menus-contents">
                <%= f.text_field :third, class:"price-input" %>
              </div>
              <div class="menus-contents">
                <%= f.text_field :forth, class:"price-input" %>
              </div>
              <div class="menus-contents">
                <%= f.text_field :fifth, class:"price-input" %>
              </div>
            </div>
          </div>
        </div>
    <div class="sell-btn-contents">
      <%= f.submit "たんぱくケア" ,class:"sell-btn" %>
    </div>
    <div class="sell-btn-contents"> 
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    </div>
    <% end %>
  </div>
<div>

app/views/proteins/show.html.erb
<%= render "shared/header" %>

<div class='show-menu'>
  <div class='show-contents'>
    <div class='show-top-contents'>
      <div class='bento-name'>
        <span><%= @protein.name %></span>
      </div>
      <div class='show-image-contents'>
        <div class='top-image'>
          <%= image_tag @protein.image, class:'image-top'%>
        </div>
        <div class='top-right'>
          <div class='bento-price'>
            <span class='price-bento'><%= @protein.price%>円(税抜）</span>
            <ul class='menu'>
              <li class= 'food'><%= @protein.first %></li>
              <li class= 'food'><%= @protein.second %></li>
              <li class= 'food'><%= @protein.third %></li>
              <li class= 'food'><%= @protein.forth %></li>
              <li class= 'food'><%= @protein.fifth %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class='center-contents'>
      <div class='show-cneter-contents'>
        <div class='show-contents-center'>
          <h3 class='nut'>栄養成分</h3>
        </div>
      </div>
      <div class='nut-contents'>
        <div class='contents-nut'>
          <div class='show-nut'>
            <p class= 'nut-lists'>エネルギー</p>
            <p class='nut-list'><%= @protein.energy%>kcal</p>
          </div>
          <div class='show-nut'>
            <p class= 'nut-lists'>たんぱく</p>
            <p class='nut-list'><%= @protein.prote %>g</p>
          </div>
          <div class='show-nut'>
            <p class= 'nut-lists'>脂質</p>
            <p class='nut-list'><%= @protein.Lipid%>g</p>
          </div>
          <div class='show-nut'>
            <p class= 'nut-lists'>塩分</p>
            <p class='nut-list'><%= @protein.salt%>g</p>
          </div>
          <div class='show-nut'>
            <p class= 'nut-lists'>炭水化物</p>
            <p class='nut-list'><%= @protein.carbo%>g</p>
          </div>
        </div>
      </div>
      <div class='center-right'>
        <% if user_signed_in? %>
          <% if current_user == @user || current_user.admin? %>
            <div class='btn-blue'>
              <%= link_to '商品の編集', edit_protein_path, method: :get,class: 'item-blue-btn'%>
            </div>
            <div class='btn-red'>
              <%= link_to '削除', protein_path, method: :delete, class: 'item-red-btn'%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="cart-buy-btn">
      <%= button_to 'カートに入れる', cart_items_path(protein_id: @protein), class: 'btn-buy'  %>
  </div>
  </div>